CREATE TABLE IF NOT EXISTS recharge_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  phone_id INT UNSIGNED DEFAULT NULL,
  phone VARCHAR(11) NOT NULL COMMENT '号码（反规范化，审计永久保留）',
  carrier ENUM('mobile','unicom','telecom') NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  trigger_type ENUM('scheduled','manual','low_balance') NOT NULL,
  triggered_by VARCHAR(100) DEFAULT NULL COMMENT '手动时记录操作人，自动时记录cron',
  adapter_name VARCHAR(64) NOT NULL COMMENT '使用的适配器名称',
  adapter_order_id VARCHAR(255) DEFAULT NULL COMMENT '聚合商侧订单号',
  status ENUM('pending','success','failed','timeout') NOT NULL DEFAULT 'pending',
  error_message TEXT DEFAULT NULL,
  balance_before DECIMAL(10,2) DEFAULT NULL,
  balance_after DECIMAL(10,2) DEFAULT NULL,
  retry_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  parent_log_id BIGINT UNSIGNED DEFAULT NULL COMMENT '重试时指向原始记录',
  next_retry_at DATETIME DEFAULT NULL COMMENT '下次重试时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME DEFAULT NULL,
  FOREIGN KEY (phone_id) REFERENCES phone_numbers(id) ON DELETE SET NULL,
  INDEX idx_phone_id (phone_id),
  INDEX idx_status (status),
  INDEX idx_created (created_at),
  INDEX idx_next_retry (next_retry_at),
  INDEX idx_parent (parent_log_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
